---
# tasks file for Kubernetes

- name: Create the pre-flight directory
  file:
    dest: "{{ pre_flight_dir }}"
    state: directory
    mode: 0600
  tags:
    - local

- name: Get the cfss & kubectl binaries
  get_url:
    url: "{{ item }}"
    dest: "{{ pre_flight_dir }}/{{ item | urlsplit('path') | regex_replace('^(.*)/(.*)_(.*)$', '\\2') }}"
  with_items:
    - "https://pkg.cfssl.org/R1.2/cfssl_linux-amd64"
    - "https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64"
  tags:
    - local
